### ISSUE TITLE
on OSX

### ISSUE THREAD

**Issue by 2johjoh2** [cschol/vcv-plugindownloader#2]
Cloning github repo led to a (small) naming error in the directory (`vcv-plugindo`**w**`loader` instead of `vcv-plugindo`**wn**`loader`).
Also : didn't have permission to execute the program, so had to execute a `sudo chmod +x vcv-plugindownloader.py` first

**Comment by cschol** [comment]
Well...sh00t. That typo is embarrassing. I'll have to fix that.

I'll add the note about permissions to the README. Thanks for reporting.

**Comment by cschol** [comment]
Fixed repository name. See the [GitHub documentation](https://help.github.com/articles/renaming-a-repository/) on how to update your local clones.

Added note about permissions in 6d91ed51b74b4e2f9fec48f97e23b35ea1b0bf85.
