### ISSUE TITLE
Feature request : have subdir in "Community" where the repo's without binaries can be found

### ISSUE THREAD

**Issue by 2johjoh2** [cschol/vcv-plugindownloader#3]
The title says it all basically : a subdir containing either weblinks to repo's that have no binaries
Alternatively : log/textfile containg the URL's 

BTW : looks great so far !!!

**Comment by cschol** [comment]
Are you talking about the [community](https://github.com/VCVRack/community) repository?
That repository is maintained by the VCV Rack developers. I just access the information in it.

`vcv-plugindownloader` tells you in its console output, which repositories do not have binaries. If you use the `-s` option to build those plugins from source, the directory with the plugin source code will have the `.git` suffix added.

If you just want to **know**, which repositories don't have binaries:

```
./vcv-plugindownloader/vcv-plugindownloader.py win | grep "No binary"
```

**Comment by 2johjoh2** [comment]
Many thx for the detailed answer !
Special bonus for the last line : not only a direct elegant solution, but also an incentive to look at what grep could do for me …

Cheers !!
