### ISSUE TITLE
mscHack build fix

### ISSUE THREAD

**Issue by ndrspcfd** [cschol/vcv-plugindownloader#4]
Hi, thanks for the script!

I noticed mscHack falls foul of the "checkout latest tag" logic, because the script tries to build 4.x which fails, whereas just building the master branch succeeds (against Rack v0.5.1 tag.)

So I'd suggest applying:

```
 PLUGIN_COMMITTISH_MAP = {
-    "Fundamental": "v0.5.1"
+    "Fundamental": "v0.5.1",
+    "mscHack": "master"
 }

```

to correct this.

You might also like to consider running `git submodule update --init --recursive` immediately prior to `make` since this fixes the build for one other plugin (can't remember which one right now) and is harmless and free if no submodules exist. It throws the AepelzensParasites plugin, but that fails anyway because it needs a specific git submodule command as per its README.

**Comment by cschol** [comment]
Thank you! `mschack` and submodule update fixed in 30feec458b527c5716ef4a4b0b857b764328876.
